---
abstract: "Perform a critical path analysis over a Graph Object, by Ded MedVed\r"
author:
  - 'Ded MedVed <dedmedved@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-CriticalPath
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Graph: 0.94
  IPC::System::Simple: 0
  Mouse: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  perl: 0
  version: 0
version: 0.04
